name: Deploy Documentation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          
      - run: pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2
      
      - run: mkdocs build --strict
        working-directory: ./docs-project
      
      - run: mkdocs gh-deploy --force
        working-directory: ./docs-project
        if: github.ref == 'refs/heads/main'